### ISSUE TITLE
Implement XDG_BASE_DIRECTORY for config

### ISSUE THREAD

**Issue by hyblm** [alanvardy/tod#128]
Use `XDG_CONFIG_HOME` environment variable to determine `config_path`, and check for the default value of `XDG_CONFIG_HOME` (which is `~/.config`). According to the spec it would also be better to generate the config in `XDG_CONFIG_HOME` instead of `~`.

I've already looked briefly through the code and it seems the `config::generate_path()` function is the thing to modify.

I'd like to try and implement this myself, but I wanted to make an issue first to discuss.

**Comment by alanvardy** [comment]
Hello @hyblm ! I like this change, my only issue is that releasing it will break configuration for existing users that are updating from a previous version. It's important to me that people be able to update fearlessly.

Maybe we could modify code so that if configuration does not exist in `XDG_CONFIG_HOME` but does exist in `~/`, copy the file over and print to the terminal that the action took place.

What do you think? You are welcome to open a PR :+1:

**Comment by hyblm** [comment]
Sounds great, I'm happy you like the change.

Many applications still check in both locations. I think we could do that as well, maybe just printing a message for existing users letting them know that `XDG_CONFIG_HOME` is now an option.

**Comment by alanvardy** [comment]
Done, thank you @hyblm
