### ISSUE TITLE
Initial setup error/config issue

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#213]
When running tod for the first time, you get the setup wizard. However, if you don't also run with any parameters, after entering your API key and configuring your timezone, you will get the error message "Unrecognized input. For more information try --help".

I went in loops several times until I realized I just missing a parameter 🤦‍♂️ It would be helpful if the script could do one or more of the following:

1) Returned a "setup successful" message after the initial configuration completes
and/or
2) Simplify the message that no parameters were specified to clearly point it out.

It would also be nice if you added command line switches for re-running setup (so I can more easily change config without deleting the config file)

Thanks again for your work on this useful software!

**Comment by alanvardy** [comment]
Hi @stacksjb !

This sounds like a great idea, my takeaways:

1. Make an explicit `init` switch that confirms if you would like to delete the config if it exists and then does the rest.
2. Add a "Config successfully created in [directory]" notification
3. Improve the error message when input is unrecognized (specify that it needs parameters)

**Comment by stacksjb** [comment]
Absolutely - thanks!

**Comment by alanvardy** [comment]
Thank you for the feedback, I improved the messaging so that it is visible when the config is created and differentiated between bad input and no input.

I was halfway through implementing init and realized that it doesn't fit nicely as most of the externally exposed functionality finds or creates a config, adding `init` would mean me just creating a function that does nothing and that would probably be confusing.

Appreciate the issue!
