### ISSUE TITLE
Add priority flad to tod task create

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/tod#336]
Here are the docs for create task on the Todoist API https://developer.todoist.com/rest/v2/#create-a-new-task

Add a priority flag to the `tod task create` command. There is no default. It only accepts values from 1 to 4.

```bash
tod task create --priority 3
```

**Comment by titoOdUA** [comment]
I am a little bit confused, maybe you can help me if you have time of course =)

Todoist has 2 APIs. Sync and Rest. As I understand both have all the functionality that one could need.
But in the `tod` we use sync and rest in some cases. Are there some limitations? or is it just easier to do some stuff in rest API?

---

I see that we create tasks via sync. Firstly it is created in the inbox, and after that, it moves to the target project.

```rust
/// Add item to project with natural language processing
pub fn add_item_to_project(
    config: &Config,
    content: String,
    project: &str,
) -> Result<String, String> {
    let item = request::add_item_to_inbox(config, &content)?;

    match project {
        "inbox" | "i" => Ok(green_string("✓")),
        project => {
            request::move_item_to_project(config, item, project)?;
            Ok(green_string("✓"))
        }
    }
}
``` 

Are there some limitations to creating a task in a specific project?

---

I see that priority update is done via rest, and there are some hard-to-understand manipulations with priority across the project. Can you take me up to speed in that regard?

like

why there is a shift in digits?

```rust
pub fn set_priority(config: &Config, item: items::Item) {
    println!("{}", item.fmt(config, FormatType::Single));

    let options = vec!["1", "2", "3"].iter().map(|s| s.to_string()).collect();
    let priority =
        config::select_input("Choose a priority from 1 (lowest) to 3 (highest):", options)
            .expect("Please enter a number from 1 to 3");

    match priority.as_str() {
        "1" => {
            let config = config.set_next_id(&item.id);
            request::update_item_priority(config, item, 2).expect("could not set priority");
        }
        "2" => {
            let config = config.set_next_id(&item.id);
            request::update_item_priority(config, item, 3).expect("could not set priority");
        }
        "3" => {
            let config = config.set_next_id(&item.id);
            request::update_item_priority(config, item, 4).expect("could not set priority");
        }
        _ => println!("Not a valid input, please enter 1, 2, or 3"),
    }
}
```

why is there this mapping?

```rust
    fn priority_value(&self) -> u8 {
        match self.priority {
            2 => 1,
            3 => 3,
            4 => 4,
            _ => 2,
        }
    }
```

**Comment by titoOdUA** [comment]
I just exploring the project little by little I am sure that with time I will eventually grasp it all, but if you can provide some info it would be great)

Regarding the priorities and this feature.

What would you say to a little refactoring of the priority situation (I am not sure what would be better or easier do it before or after this feature)

How about we introduce some enum for priority? something like
```rust
enum TaskPriority {
    URGENT(u8)
    //....
}
```
and impl From trait for it so we can get the user string and convert it to an enum value and afterward work with strongly type value instead of some 1,2,3,4 strings

we can that store it in Item struct

```rust
struct Item {
    //...
    pub priority: TaskPriority //instead of u8
    //...

}
```

**Comment by alanvardy** [comment]
> Todoist has 2 APIs. Sync and Rest. As I understand both have all the functionality that one could need.
> But in the tod we use sync and rest in some cases. Are there some limitations? or is it just easier to do some stuff in rest API?

 The sync API has fewer options but supports natural language processing, i.e. "Get milk today" as content will put "Get milk" on a ticket and date it as due today.

The rest API has more options but no natural language support.

I think that you will need to use the REST API but be sure to double-check!

> Are there some limitations to creating a task in a specific project?

Yes, this was a limitation of the sync API and I think that it still is.

Some of my context around these things is 2 years old and came from experimenting around with undocumented API behavior, so things may have changed! I would love to remove use of the sync API if it is possible.


> I see that priority update is done via rest, and there are some hard-to-understand manipulations with priority across the project. Can you take me up to speed in that regard?

Yes, this part of the code is a bit clunky isn't it. The API has 4 different priority levels: 1 to 4 with 4 being the highest.

When making the API I considered 1 to be "not prioritized" as it is the default ticket priority and 2 to 4 to be low to high. And thus I reassigned 2-4 to be 1-3 in the user interface.


> why is there this mapping? (priority value)

When determining which task to process next they are ranked by value, this function determines the value of the priority. In this case, "unknown" (priority 1) has a higher rank than "low" (priority 2).

> What would you say to a little refactoring of the priority situation (I am not sure what would be better or easier do it before or after this feature)

I think that this is an excellent idea, I would suggest doing the refactor first, and then after we merge you can continue to do the priority flag :+1:

**Comment by stacksjb** [comment]
Re the comments about Todist API, this is largely correct. QuickAdd is only available through Sync API.

It's recommended to use Sync API if you are maintaining a local copy and need to do differential updates, but the REST API is easier to code with and more straightforward.

Happy to discuss further if there might be one or the other that might be better for the use case. If you are creating tasks in specific project/priority/label, it woudl seem to be that it would be more effective to create using the appropriate API to create it directly instead of moving it around after. (I believe a side effect of this method though is that if you create a task in a project or with a label that doesnt' exist, it will create the project/label instead of returning an error)

**Comment by alanvardy** [comment]
Done!
