### ISSUE TITLE
Error occurs when attempting to create a task in my setup

### ISSUE THREAD

**Issue by acevif** [alanvardy/tod#372]
I encountered an error while trying to create a task in my current setup. Here's the error message I received:

```
$ tod task create
> Content Buy more milk today
> Choose a priority that should be assigned to task: LOW
The prompt configuration is invalid: Available options can not be empty
```

quickadd works fine:
```
$ tod -q Buy more milk today test 22
✓
```

**Configuration:**

```
$ cat ~/Library/Application\ Support/tod.cfg
{
  "last_version_check": null,
  "mock_url": null,
  "next_id": null,
  "path": "/Users/acevif/Library/Application Support/tod.cfg",
  "projects": {},
  "spinners": true,
  "timezone": "Japan",
  "token": "0000000000000000000000000000000000000000"
}%
```

**Environment:**

* macOS Ventura 13.4（22F66）

```
$ rustc --version
rustc 1.69.0 (84c898d65 2023-04-16) (built from a source tarball)
$ uname -a
Darwin oishimasayoshi.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64
```

Please let me know if there's any additional information I can provide to help resolve this issue.

Thanks.

**Comment by alanvardy** [comment]
Hello @acevif, and thank you for the bug report!

The issue is occurring because there are no projects stored in your config and `tod task create` was looking there for a project to list in the select options.

I don't think that the error message was evident at all, though; I would like it to instruct the user instead to use `tod project import` to select the projects they would like to import into config.

Does that sound reasonable?

**Comment by acevif** [comment]
@alanvardy Oh, thank you! It's working now.
After running the 'tod project import' command, it's functioning properly in my setup.

> Does that sound reasonable?

Yes!
It would be beneficial for users, especially newcomers like myself :)
