### ISSUE TITLE
Relative file path implementation

### ISSUE THREAD

**Issue by rvbcldud** [alanvardy/tod#609]
Hello! I am a new user of tod and while setting up my config, I attempted to use a relative file path for my config file. I soon realized it had to be absolute but would love to see tod support relative file paths with "~" ... Let me know if this would be a good first issue and I can even try and tackle it. 

Thank you!

**Comment by rvbcldud** [comment]
Thank you, Alan. That would be great. I have taken a look through the codebase while figuring out the config. However, could you give me a good place to start?

**Comment by alanvardy** [comment]
Definitely. All the logic you need to change would be in the config file

https://github.com/alanvardy/tod/blob/main/src/config.rs

There are a few different functions that would need to be changed: `load` `create` `save` etc, anywhere you see an `fs` call basically. I would consider first extracting some of those calls into a private function or 3 so that you can make all the changes in one place, and then making the change. Feel free to open up a WIP PR and tag me for input too!

**Comment by alanvardy** [comment]
Completed :+1:
