### ISSUE TITLE
Don't empty or label child tasks

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/tod#611]
Tod doesn't support child (sub) tasks and can mess them up if it tries to process them. Skip over processing all child tasks.

**Comment by stacksjb** [comment]
Aren't child/sub tasks identical to regular tasks, except they have a parent_id? 

It seems to me that would be very easy to handle - just leave the parent_ID as-is if present? (just thinking out loud here).

**Comment by stacksjb** [comment]
After reviewing the API documentation (https://developer.todoist.com/rest/v2/#tasks), from what I can tell, parent_id and section_id are read-only, so updating a task shouldn't make a difference if it is a subtask or parent task. It looks like they can only be provided when it is a new task.

I haven't heavily used subtasks with tod so I might be unclear on what the logic needs to be - is there a use case I can test here and debug?

**Comment by alanvardy** [comment]
Hi @stacksjb !

I think that the problem I was encountering was that I was using `tod project empty` and it was prompting me to move subtasks, and if I moved the subtask to the new project it removed the parent id.

I need to retest this, my memory is fuzzy.

**Comment by stacksjb** [comment]
The above is correct - if you move a subtask it would no longer be a subtask.

The other thing to keep in mind is that if you complete a parent task, it automatically completes all subtasks.

It depends on the use case here - normally you would want to complete subtasks individually, not the parent task, but maybe people want the parent task. 

For me, I don't usually add subtasks until I have a more complex initial task. However, because i work off labels, the subtasks don't usually show up anyway unless they are in the context. 

Going to have to think about this more... maybe the best way would be to add logic to ignore all parent tasks with children (only show subtasks) for all process & next actions, and do the inverse (ignore all child tasks) for the "empty" and similar assign tasks?

**Comment by alanvardy** [comment]
Interesting. This sounds like two tickets now. Splitting out the work and closing this ticket!

- https://github.com/alanvardy/tod/issues/651
- https://github.com/alanvardy/tod/issues/652
