### ISSUE TITLE
Prompt initial user to set up config

### ISSUE THREAD

**Issue by rvbcldud** [alanvardy/tod#613]
When a new user installs tod and runs it for the first time (i.e., types "tod" and hits enter), I do not think it prompts the user to set up the config. It will only set up the config when an API request is made (e.g., "tod task list").

I think prompting the user to set up the config regardless of whether a command is given or not would be a useful addition in order to make the interface more friendly.

Let me know what you guys think!

**Comment by alanvardy** [comment]
This behaviour (just displaying help when `tod` is run, without taking any other action) is controlled by the clap library.

![image](https://github.com/alanvardy/tod/assets/38899847/bf737f5f-12a7-4e08-b4f0-182791be4937)

I wonder if clap can run a function instead of displaying help, so that the config can be created and THEN help is displayed.

**Comment by alanvardy** [comment]
Looks like something not supported out of the box by clap. Upon further consideration I like the idea of it just displaying help.

I will add a config command for entering an API key or changing it later 👍
