### ISSUE TITLE
Becoming a collaborator

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/tod#772]
@stacksjb, would you like me to add you as a collaborator to this repository? It would allow you to create branches in this repo, and you wouldn't have to use a fork anymore. It would also be easier for me to pull down your work and run the code locally.

**Comment by stacksjb** [comment]
That'd be great, especially then because I could tag and work on issues, labels, templates etc, thx!

As long as there are still the appropriate PR review approval requirements so that I can't accidentally approve a PR without your review (not that I would intentionally, but would prefer that). Do you have "Require review from code owners" and'or the main branch as a "protected branch?"

(see https://github.com/orgs/community/discussions/69459 and https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)

![image](https://github.com/alanvardy/tod/assets/2865491/ba4c5306-330f-4483-8446-b0608c430b42)

**Comment by stacksjb** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule -> this is the correct link for checking branch protection rules

**Comment by alanvardy** [comment]
I added a CODEOWNERS with myself as the only one, and sent an invite. Welcome aboard!

**Comment by stacksjb** [comment]
Thx! Glad to help. 

Validated that it is setup correctly

<img width="503" alt="image" src="https://github.com/alanvardy/tod/assets/2865491/20feab42-7b45-4543-9370-5bee6010d553">

Thx!

**Comment by stacksjb** [comment]
Also let me know any branch naming syntax - probably make sense to have a dev/prod (main) type branches with the protections on the main branch - that way I can create branches and then close them as needed, and submit them to a dev branch that then can get pulled ot the main branch (that's the step that I would then automate to release).

Right now I see a lot of different branches, so I'll probably follow suit and just create a new one (which can be deleted/archived) with any commits :)

Thanks!

**Comment by alanvardy** [comment]
The only branch that matters is `main`. I use trunk-based development and work to keep features as small as possible, merging regularly. Once enough changes have built up, I sanity check and release. 

The Rust compiler has been wonderful for preventing many errors (e.g., type errors); it's pretty much just logic errors that we need to look out for. So feel free to use any branch convention you like; I just ask that the PRs be as bite-sized as possible and get merged regularly.
