### ISSUE TITLE
Re-enable config::tests::test_maybe_expand_home_dir

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/tod#809]
This test fails on the windows platform. Rewrite the test so that it is platform agnostic.

Assigning this to you @stacksjb as I am running Linux only and can't confirm locally.

**Comment by stacksjb** [comment]
Thx! I think we will need to replace it with a multiplatform test as it will be platform specific.

**Comment by stacksjb** [comment]
Looking at this test, I see a few ways to do it:
1) Make platform-specific compilation tests - either in one test or as individual platform specific tests (i.e.)
`
#cfg(target_os = "linux")]
//linux test here
`
`
#cfg(target_os = "macos")]
//macos test here
`
`
#cfg(target_os = "windows")]
//windows test here
`
`

It looks like the code is using https://docs.rs/homedir/latest/homedir/ to get the homedir - I wanted to note that this is also unnecessary because dirs is already present, which provides a function to retrieve this. I'll update this to clean up the function.

**Comment by rvbcldud** [comment]
Good catch! I was the one that initiated this change and was not as familiar with the code base. And so, I did not know we already had dirs.

Looking forward to seeing these changes

**Comment by alanvardy** [comment]
Addressed :+1:
